<head> 
	<link rel="stylesheet" type="text/css" href="someCss.css">
	<script src = "./someJs.js" type="text/javascript"> </script>
</head>
<body onload="displayBox(removeBox);">
	<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse et ipsum non sem consectetur convallis. Donec consequat, ante et dignissim accumsan, odio velit aliquam mauris, sed egestas arcu quam a magna. Nunc placerat est eu lectus faucibus, eu suscipit nulla egestas. Proin ipsum arcu, tristique ut rutrum quis, vehicula id purus. Aenean et venenatis orci. Nullam vulputate, dui vitae ultrices mattis, ipsum metus consequat turpis, in tristique mauris sem ut urna. Nulla et luctus lectus. Phasellus sed tincidunt ligula.

Nunc scelerisque rhoncus consectetur. Sed ullamcorper convallis felis in luctus. Sed elementum ante sed condimentum mollis. Donec viverra, enim ac elementum dapibus, odio orci hendrerit nisi, venenatis congue dui enim eget nisl. Curabitur feugiat magna ac erat tincidunt faucibus. Donec ullamcorper odio eros, ac laoreet justo fermentum nec. In dictum lacus sit amet leo tempus, eget pulvinar elit blandit. Duis pellentesque vestibulum arcu, mollis luctus erat sodales eu. Etiam pulvinar tellus ut tortor suscipit ullamcorper. In id hendrerit orci, vel finibus sapien. Nam ornare eu ipsum sit amet facilisis. Curabitur eget auctor tortor.

Nulla eu arcu massa. Donec pharetra quam accumsan dolor pretium, et condimentum augue ullamcorper. Quisque accumsan ligula at enim interdum fringilla. Curabitur auctor, lorem in pretium luctus, nisi enim bibendum felis, eu tincidunt nisi metus in felis. Maecenas euismod purus eu lacus tempor semper. Nam faucibus rutrum lectus sit amet vestibulum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Curabitur vitae hendrerit sapien. Donec lacinia eleifend purus nec aliquet. Phasellus id dolor sit amet leo auctor interdum. Nunc vitae nibh pretium mi dignissim pharetra. Proin posuere, leo ac pulvinar commodo, leo lectus facilisis est, quis cursus augue felis id magna. Pellentesque pretium nec leo nec tempor. Sed interdum, mauris vitae fermentum rutrum, ipsum nulla malesuada massa, nec imperdiet nisi magna ac purus. Praesent eu odio quis nunc interdum iaculis. Donec imperdiet tristique augue ac volutpat. Nunc varius ligula suscipit, maximus erat vel, rutrum erat. In auctor lectus ut blandit venenatis. Nullam lacus felis, congue ac lacus non, mollis rutrum urna. Suspendisse potenti. Etiam dapibus felis massa, nec convallis massa aliquet sit amet. Vestibulum at quam vehicula, ultrices diam efficitur, feugiat sem.

Curabitur et metus ligula. Ut sed enim non tellus dignissim gravida a vitae neque. Donec id ligula at justo imperdiet pulvinar. Donec auctor sagittis volutpat. Quisque et porta nibh. Nulla ultrices tincidunt iaculis. Proin eget magna arcu. Etiam dignissim tellus mollis felis consectetur tincidunt. Donec sodales posuere eros, ac eleifend ex aliquam nec.

Curabitur euismod, ligula eu auctor placerat, ante lorem malesuada ipsum, ut venenatis nisi libero eu dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vitae hendrerit neque. Sed sagittis velit at maximus egestas. Quisque efficitur convallis velit, nec convallis ligula facilisis at. Praesent in elementum orci, in venenatis ex. Aenean tempor felis eu luctus tristique. Vestibulum vitae est nec lectus hendrerit accumsan. Curabitur massa ante, sagittis id tempor quis, semper at purus. Proin tincidunt tellus turpis, sit amet semper est tempor id. Etiam urna arcu, molestie et dapibus id, gravida eget nibh. Nam eget lacinia ipsum.

Integer efficitur quis lectus ut venenatis. Maecenas finibus tempus tortor a congue. Maecenas eu convallis leo, non dignissim felis. Vestibulum varius lacinia gravida. Fusce porta tellus ligula, ut aliquet magna luctus quis. Sed nec enim interdum, suscipit erat sit amet, ultricies nibh. Donec sem erat, porta ac volutpat interdum, fermentum ornare velit. Etiam vel facilisis nisl. Integer interdum eu nisi et consectetur.

Fusce aliquam accumsan malesuada. Integer mattis porta purus, dapibus vulputate nulla. Phasellus sit amet consectetur lorem. Aliquam quis sollicitudin leo, nec ultrices libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla ultricies mi nisl, ac malesuada risus malesuada eu. Suspendisse sed porta diam. Pellentesque mattis egestas nunc a imperdiet.

Quisque eget eros sit amet enim facilisis porta vitae nec tortor. Duis aliquet mauris eu libero feugiat bibendum. Proin euismod, dolor at aliquet faucibus, est justo viverra massa, quis tristique velit sapien in metus. Nunc ullamcorper pulvinar pellentesque. Nam blandit, velit non fringilla fringilla, ante massa condimentum sapien, non volutpat tortor quam vitae elit. Vestibulum scelerisque mauris quis ligula consequat bibendum. Mauris nec mi quam. Suspendisse nec felis vitae nibh suscipit pellentesque vel sed lorem. Fusce felis est, rhoncus in hendrerit at, mattis ut nisl. Ut at metus sollicitudin, ultrices massa in, pretium ipsum. Morbi vel volutpat mi, eget ullamcorper dui. Ut mollis quis justo sed finibus. Mauris vel efficitur metus, congue tempor urna. Nulla facilisi. Praesent dapibus accumsan nulla eu faucibus. Proin ipsum dui, blandit vitae sem sed, hendrerit ultricies elit.

Donec ullamcorper, leo ac sodales dictum, metus turpis egestas ipsum, et ultricies nulla odio et sem. Morbi justo turpis, aliquet eget pharetra in, feugiat vitae tortor. Mauris enim enim, porttitor non ligula tincidunt, scelerisque suscipit dolor. Maecenas magna nulla, gravida lacinia feugiat nec, blandit in leo. Proin tincidunt magna vitae gravida interdum. Curabitur sodales vulputate magna eu blandit. Cras tellus quam, facilisis ut ipsum nec, gravida laoreet nulla. Fusce posuere imperdiet ligula in tristique.

Nulla rhoncus vehicula consectetur. Praesent pharetra nisl tellus, eu venenatis dui pretium ac. Donec in dolor a mauris malesuada dictum porta quis arcu. Nullam in tempus lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean pretium massa in turpis tristique, in feugiat nibh malesuada. Sed in tellus ex. Nam ultrices, magna et accumsan luctus, tellus dolor vestibulum dui, sit amet tincidunt enim massa lobortis sem. Fusce cursus nisi ac maximus efficitur. Vestibulum quis ex odio. Suspendisse lectus nulla, tristique vitae sagittis nec, rutrum vel velit. Donec tincidunt aliquet quam, a sollicitudin turpis. Nunc bibendum eros cursus dapibus efficitur. Praesent placerat, metus vel dapibus fermentum, sapien enim consequat arcu, at ullamcorper velit justo eget nisl. Sed a est ac sapien commodo luctus eu vitae enim. Nam mattis lacinia bibendum.

Etiam eu bibendum ex. Phasellus mattis leo non nibh ornare, id sagittis augue iaculis. Praesent hendrerit pretium arcu, ut luctus ex interdum tincidunt. Praesent et dignissim odio, id pulvinar tortor. Pellentesque dictum mi at magna facilisis tempor ut id ante. Fusce imperdiet tellus eget maximus pulvinar. Nulla facilisi. Etiam gravida at tellus a malesuada. Duis vitae suscipit sapien. Etiam eu ornare leo, ac cursus velit. Praesent luctus nisi ut hendrerit luctus.

Sed placerat porta ligula ut vehicula. Donec vel finibus ipsum, quis faucibus velit. Etiam hendrerit, risus vel aliquam rhoncus, lorem erat suscipit massa, eu blandit leo erat sed ex. Duis vitae molestie justo, id tempor magna. Vestibulum vel enim commodo, volutpat ante quis, rhoncus est. Aliquam erat volutpat. Curabitur tempor eros at felis dapibus eleifend.

Proin porta, nisl vitae pellentesque lobortis, erat dui feugiat neque, at commodo lacus sem eget enim. Aenean venenatis sapien dolor, at auctor elit aliquet elementum. Nunc porta tempor metus, eget vulputate turpis lobortis at. Maecenas fermentum dapibus erat, tempus fermentum dui aliquam et. In ultricies quis ex sed elementum. Donec vel cursus ante. Cras ut elementum nibh, at aliquam risus. Suspendisse vel sem ut tellus mollis ullamcorper nec vitae enim. Donec blandit augue sed gravida viverra. In eget est a metus varius sollicitudin ac eu libero. In consectetur, nunc ac interdum gravida, magna enim luctus risus, eu luctus ex mauris nec arcu. Vivamus laoreet consectetur porttitor. Ut augue lorem, tempor sit amet placerat ut, interdum eget leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc metus sapien, placerat non imperdiet vitae, hendrerit vitae tortor. Donec mi nulla, dictum sit amet risus sit amet, rutrum efficitur lectus.

Maecenas eu fringilla dolor. Nunc maximus sagittis est, sit amet pulvinar odio ullamcorper et. Proin convallis nisl in scelerisque pharetra. Sed finibus lobortis lorem, nec vestibulum tellus sagittis et. Morbi sed varius est. Vestibulum at commodo tortor, sit amet congue libero. Fusce a est vehicula nunc finibus consequat et non enim. Nunc euismod lorem diam, id rhoncus mauris consequat non. Proin sed turpis mauris. Praesent eleifend molestie congue. Donec ac elit mauris. Praesent congue hendrerit mauris a hendrerit. Suspendisse ac massa enim. Phasellus laoreet tellus quam, ut blandit nibh interdum sagittis. Nulla mattis nisi blandit lorem vehicula, vel pellentesque elit pretium. Curabitur sagittis, est aliquam aliquam laoreet, tortor ante iaculis ligula, ut mattis mi turpis eu eros.

Proin lorem ipsum, mollis nec dapibus nec, dapibus nec nulla. Nunc eget pharetra sapien. Duis eu nunc vel erat vulputate sollicitudin. In sed semper ligula, eu auctor massa. Praesent bibendum rutrum odio a maximus. Donec a eros lacinia, fringilla dui ut, maximus ipsum. Morbi porttitor tellus et risus dictum porta. Sed faucibus dolor ac orci efficitur dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus at pharetra felis. Maecenas tortor arcu, mattis vitae fringilla non, tincidunt non diam. Sed nulla nulla, accumsan et libero id, pulvinar gravida nisl.

Morbi bibendum quam nisl, eu efficitur massa tincidunt vel. Suspendisse pretium orci nulla, vel dapibus nisl tempus ut. Donec hendrerit magna ultrices, efficitur nisi sit amet, volutpat mi. Vestibulum mi leo, aliquet a neque at, tempor malesuada odio. Vivamus hendrerit ligula facilisis dui finibus porta vel at magna. Integer eu dignissim nunc, vitae tincidunt turpis. Vestibulum fringilla dignissim felis, a iaculis magna accumsan id.

Morbi tincidunt sed sapien nec scelerisque. Donec pharetra purus augue, a finibus tellus accumsan nec. Ut vel egestas nulla. Maecenas vel ex imperdiet, ultrices arcu in, finibus leo. Sed condimentum tincidunt semper. Ut aliquet tortor dignissim urna interdum, sed viverra nisi rutrum. Cras interdum id quam in fringilla.

Suspendisse magna justo, egestas quis nisl rutrum, viverra tristique dui. Praesent sit amet purus quis ligula accumsan accumsan ut vel leo. Mauris vitae placerat lacus. Vivamus eget nunc feugiat, lacinia nulla vitae, porttitor sapien. Aliquam ullamcorper ultrices odio, in fringilla mi accumsan ac. Nulla sit amet mauris ac orci efficitur viverra sed quis nunc. Duis non metus ornare dolor interdum viverra eget nec libero. Duis rhoncus a odio at consequat. Sed scelerisque condimentum sem in vulputate. Suspendisse ultrices mauris sagittis sem sodales congue. Curabitur nulla tortor, fermentum at tincidunt sed, dictum dictum leo. Donec hendrerit diam justo, accumsan placerat leo tempus a. Donec id luctus dui, quis sagittis dui. Cras nec hendrerit quam, et congue ligula. Etiam tortor est, luctus nec molestie non, ultrices eget risus.

Donec porta ullamcorper massa, ac elementum purus feugiat vitae. Aenean condimentum felis ut massa faucibus pellentesque. Nullam tempor vulputate augue sollicitudin pulvinar. Vivamus varius, mi vitae ornare elementum, metus elit aliquet orci, id placerat ante nisl sit amet sem. Ut eget sapien id lorem lobortis ultricies non consectetur est. Curabitur convallis metus sit amet sollicitudin fermentum. Aenean convallis risus vitae nisl maximus, sit amet pharetra eros posuere. Mauris vehicula feugiat mauris porttitor imperdiet. In quis turpis vel diam laoreet scelerisque eget quis nisl.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquet ipsum nec diam dignissim pellentesque. Sed nec nisl ullamcorper mauris porta aliquet. Morbi nibh nulla, posuere vel bibendum eget, gravida nec nulla. Donec quis ipsum lorem. Donec tristique augue ac lacus volutpat egestas. Nam vestibulum volutpat nunc, sed luctus sapien congue at. Nulla facilisi. Quisque ut metus vitae risus maximus maximus. Pellentesque at vulputate nisl. Nunc nec viverra nibh. Nunc pulvinar, ligula eu lobortis aliquam, neque sem consectetur risus, in eleifend massa velit non orci. Ut tincidunt a libero eget vulputate. Curabitur eleifend in purus eu tincidunt. Phasellus sit amet suscipit risus, id interdum enim. Pellentesque finibus congue neque facilisis scelerisque.

Maecenas gravida quis diam id venenatis. Donec pretium velit enim, eget ultricies ipsum lobortis at. Quisque urna diam, blandit et consectetur vel, placerat in nisi. Suspendisse vel tortor eu quam scelerisque hendrerit vitae congue mi. Pellentesque posuere gravida lorem, ac mattis elit tristique vitae. Sed quis pulvinar augue. Aenean dignissim laoreet velit, ac euismod massa porttitor eget. Integer sit amet ante fermentum, aliquet orci in, tincidunt augue. Nullam porta, eros in vestibulum volutpat, mi sapien sagittis eros, ultricies egestas nunc urna et turpis. Donec a lectus et metus volutpat facilisis. Sed porta cursus eros, eu dapibus eros sagittis sed. Donec mollis ullamcorper lectus, eget molestie ex semper at. Nullam bibendum elit id felis maximus, ac ultricies mi ultricies. Aliquam erat volutpat. Fusce scelerisque turpis eu nibh elementum, vel mattis mauris mollis.

Donec sodales tristique ligula, eu ultrices neque. Sed massa tellus, tincidunt ac hendrerit tincidunt, cursus ac mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc non velit at lacus ultricies feugiat ut eu ipsum. Integer sollicitudin pharetra sem ac fringilla. Fusce tempor sollicitudin enim lacinia ornare. Nunc tortor nibh, tristique vitae tempor non, pretium ut dui. Cras sit amet nulla mi. Nulla quam mauris, rhoncus vitae eleifend sit amet, gravida non dui. Cras lacinia, tellus laoreet pharetra laoreet, dolor mi auctor quam, id laoreet orci libero quis nisi. Etiam non egestas nisi, nec rhoncus enim. Vivamus diam lorem, tristique vitae eros ut, fermentum elementum felis. Sed iaculis vehicula egestas. Fusce auctor porta venenatis. Nulla fringilla in eros eu tincidunt. Etiam tempor dui vel nulla viverra, ut feugiat metus dignissim.

Nullam quis est ullamcorper, porttitor ipsum vel, congue nibh. Duis rhoncus tempor dolor in vestibulum. Morbi lectus nisl, fringilla vel nisl ac, dictum sodales massa. Nunc ut pharetra arcu. Proin ullamcorper felis id placerat aliquam. Sed tincidunt rhoncus dapibus. Aenean sit amet fermentum odio. Etiam nisl lectus, vestibulum ac bibendum vitae, auctor sed sapien. Pellentesque eget purus metus. Mauris ultricies arcu eget sollicitudin lacinia. Nulla vel sodales risus. Vestibulum aliquam in diam id ornare. Aenean maximus elit in auctor rutrum.

Suspendisse libero est, hendrerit eget rhoncus id, volutpat at quam. Duis ultricies dui vel ultrices interdum. Sed quis nulla non nulla auctor mattis. Etiam accumsan hendrerit ante, vel pharetra leo pharetra a. Aliquam posuere nulla id nisl lacinia, vitae volutpat ipsum dictum. Proin sit amet sem lacinia, elementum enim in, maximus velit. Sed placerat varius ante, tristique mattis diam laoreet sit amet. Pellentesque feugiat cursus bibendum. Pellentesque eget velit non sapien interdum euismod. In feugiat libero quis enim tempus, sed sodales urna cursus. Sed a massa vehicula, euismod sem eget, scelerisque lectus. Curabitur mollis mi in bibendum vulputate. Sed ut imperdiet lectus. Nunc convallis venenatis tincidunt.</div>
	<div id="someBox">
		<div id="box_header">
			<img src="./i_icon.png" style="line-height: 1px; vertical-align: bottom; margin-right: 5px" height="20" width="20" />Tutorial 1 : Basics
		</div>
		<div id="box_body">
			Welcome to King's Conquest. In this tutorial, you will learn to move a unit, attack an enemy, and win the game by killing the enemy king.<br /><br />
		</div>
		<div id="box_foot">
			<button type="button" id="actionButton" class="btn" ng-click="">OK</button>
		</div>
	</div>
</body>