function start_replay(){
setTimeout(function(){ handleOpponent({"error_code": 0,"actions": [{"action_type": "move_unit", "unit_id": 88,"path": [[3,2]]},{ "action_type" : "update_unit", "unit_id" : 88, "canMove" : 0, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0}]}); }, 0);
setTimeout(function(){ handleOpponent({"error_code": 0,"actions": [{ "action_type" : "update_unit", "unit_id" : 88, "canMove" : 0, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 89, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 90, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 91, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 92, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 93, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 94, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 95, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 96, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 97, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{"action_type": "turn_change", "new_turn": 1,"effects_to_apply": [],"units_new_cd": [],"buffs_to_remove": []},{"action_type" : "update_gold", "gold" : 510, "team" : 0},{"action_type" : "update_gold", "gold" : 510, "team" : 1}]}); }, 0);
setTimeout(function(){ handleOpponent({"error_code": 0,"actions": [{ "action_type" : "update_unit", "unit_id" : 88, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 89, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 90, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 91, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 92, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 93, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 94, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 95, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 96, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 97, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{"action_type": "turn_change", "new_turn": 0,"effects_to_apply": [],"units_new_cd": [],"buffs_to_remove": []},{"action_type" : "update_gold", "gold" : 520, "team" : 0},{"action_type" : "update_gold", "gold" : 520, "team" : 1}]}); }, 0);
setTimeout(function(){ handleOpponent({"error_code": 0,"actions": [{"action_type": "move_unit", "unit_id": 98,"path": [[11,2],[10,2],[9,2],[8,2]]},{ "action_type" : "update_unit", "unit_id" : 98, "canMove" : 0, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0}]}); }, 0);
setTimeout(function(){ handleOpponent({"error_code": 0,"actions": [{"action_type": "apply_buff", "buff_id": 2,"unit_id": 98},{"action_type" : "trigger_buff", "buff_effect" : "IncAttack", "unit_id" : 98, "health_change" : 0 },{ "action_type" : "update_unit", "unit_id" : 98, "canMove" : 0, "canAttack" : 0, "outOfMoves" : 1, "skillCoolDown" : 6}], "debug": "Battle Cry"}); }, 0);
setTimeout(function(){ handleOpponent({"error_code": 0,"actions": [{ "action_type" : "update_unit", "unit_id" : 98, "canMove" : 0, "canAttack" : 0, "outOfMoves" : 1, "skillCoolDown" : 5},{ "action_type" : "update_unit", "unit_id" : 99, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 100, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 101, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{"action_type": "turn_change", "new_turn": 1,"effects_to_apply": [],"units_new_cd": [],"buffs_to_remove": []},{"action_type" : "update_gold", "gold" : 1010, "team" : 0},{"action_type" : "update_gold", "gold" : 1010, "team" : 1}]}); }, 0);
setTimeout(function(){ handleOpponent({"error_code": 0,"actions": [{"action_type": "move_unit", "unit_id": 100,"path": [[2,11],[2,10],[2,9],[2,8]]},{ "action_type" : "update_unit", "unit_id" : 100, "canMove" : 0, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0}]}); }, 0);
setTimeout(function(){ handleOpponent({"error_code": 0,"actions": [{"action_type": "game_end", "reason":"quit_game","winner": 0}]}); }, 0);
setTimeout(function(){ handleOpponent({"error_code": 0,"actions": [{"action_type": "move_unit", "unit_id": 139,"path": [[0,3],[0,4],[1,4],[2,4]]},{ "action_type" : "update_unit", "unit_id" : 139, "canMove" : 0, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0}]}); }, 5000);
setTimeout(function(){ handleOpponent({"error_code": 0,"actions": [{"action_type": "move_unit", "unit_id": 137,"path": [[3,3],[3,4],[3,5],[4,5]]},{ "action_type" : "update_unit", "unit_id" : 137, "canMove" : 0, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0}]}); }, 8000);
setTimeout(function(){ handleOpponent({"error_code": 0,"actions": [{ "action_type" : "update_unit", "unit_id" : 135, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 136, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 137, "canMove" : 0, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 138, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 139, "canMove" : 0, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 140, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 141, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 142, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 143, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{ "action_type" : "update_unit", "unit_id" : 144, "canMove" : 1, "canAttack" : 1, "outOfMoves" : 0, "skillCoolDown" : 0},{"action_type": "turn_change", "new_turn": 1,"effects_to_apply": [],"units_new_cd": [],"buffs_to_remove": []},{"action_type" : "update_gold", "gold" : 510, "team" : 0},{"action_type" : "update_gold", "gold" : 510, "team" : 1}]}); }, 10000);
setTimeout(function(){ handleOpponent({"error_code": 0,"actions": [{"action_type": "game_end", "reason":"quit_game","winner": 1}]}); }, 12000);

}